DROP DATABASE IF EXISTS petpark_db;

CREATE DATABASE petpark_db;
USE petpark_db;

CREATE TABLE pets(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    ownerId INTEGER,
    alive BOOLEAN DEFAULT 1,
    hunger INTEGER DEFAULT 5,
    sleepy INTEGER DEFAULT 5,
    happy INTEGER DEFAULT 5,
    lastfed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastslept TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastpet TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE users(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    password VARCHAR(255)
)
